# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:\Users\lor\Documents\FastGlitch\fg.ui'
#
# Created: Fri Nov 11 13:28:48 2016
#      by: pyside-uic 0.2.15 running on PySide 1.2.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui
import func_fastglitch, os
def resource_path(relative_path):
	try:
		base_path = sys._MEIPASS
	except Exception:
		base_path = os.path.abspath(".")
	return os.path.join(base_path, relative_path)

class Ui_MainWindow(object):
	def setupUi(self, MainWindow):
		MainWindow.setObjectName("MainWindow")
		MainWindow.resize(1000, 600)
		MainWindow.setMinimumSize(QtCore.QSize(1000, 600))
		icon = QtGui.QIcon()
		icon.addPixmap(QtGui.QPixmap(resource_path("drawing.ico")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
		MainWindow.setWindowIcon(icon)
		self.centralwidget = QtGui.QWidget(MainWindow)
		self.centralwidget.setObjectName("centralwidget")
		self.horizontalLayout_2 = QtGui.QHBoxLayout(self.centralwidget)
		self.horizontalLayout_2.setObjectName("horizontalLayout_2")
		self.verticalLayout_3 = QtGui.QVBoxLayout()
		self.verticalLayout_3.setObjectName("verticalLayout_3")
		self.frame = QtGui.QFrame(self.centralwidget)
		self.frame.setFrameShape(QtGui.QFrame.Box)
		self.frame.setFrameShadow(QtGui.QFrame.Sunken)
		self.frame.setObjectName("frame")
		self.verticalLayout_4 = QtGui.QVBoxLayout(self.frame)
		self.verticalLayout_4.setObjectName("verticalLayout_4")
		self.label = QtGui.QLabel(self.frame)
		self.label.setObjectName("label")
		self.verticalLayout_4.addWidget(self.label)
		self.label_2 = QtGui.QLabel(self.frame)
		self.label_2.setObjectName("label_2")
		self.verticalLayout_4.addWidget(self.label_2)
		self.verticalLayout_3.addWidget(self.frame)
		spacerItem = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
		self.verticalLayout_3.addItem(spacerItem)
		self.horizontalLayout = QtGui.QHBoxLayout()
		self.horizontalLayout.setObjectName("horizontalLayout")
		self.frame_2 = QtGui.QFrame(self.centralwidget)
		self.frame_2.setFrameShape(QtGui.QFrame.Box)
		self.frame_2.setFrameShadow(QtGui.QFrame.Sunken)
		self.frame_2.setObjectName("frame_2")
		self.verticalLayout_5 = QtGui.QVBoxLayout(self.frame_2)
		self.verticalLayout_5.setObjectName("verticalLayout_5")
		self.label_3 = QtGui.QLabel(self.frame_2)
		sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
		sizePolicy.setHorizontalStretch(0)
		sizePolicy.setVerticalStretch(0)
		sizePolicy.setHeightForWidth(self.label_3.sizePolicy().hasHeightForWidth())
		self.label_3.setSizePolicy(sizePolicy)
		self.label_3.setAlignment(QtCore.Qt.AlignCenter)
		self.label_3.setObjectName("label_3")
		self.verticalLayout_5.addWidget(self.label_3)
		spacerItem1 = QtGui.QSpacerItem(203, 13, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
		self.verticalLayout_5.addItem(spacerItem1)
		self.label_4 = QtGui.QLabel(self.frame_2)
		self.label_4.setObjectName("label_4")
		self.verticalLayout_5.addWidget(self.label_4)
		self.RBA = QtGui.QSpinBox(self.frame_2)
		self.RBA.setMaximum(16)
		self.RBA.setObjectName("RBA")
		self.verticalLayout_5.addWidget(self.RBA)
		self.label_5 = QtGui.QLabel(self.frame_2)
		self.label_5.setObjectName("label_5")
		self.verticalLayout_5.addWidget(self.label_5)
		self.RGBD = QtGui.QSpinBox(self.frame_2)
		self.RGBD.setMaximum(64)
		self.RGBD.setObjectName("RGBD")
		self.verticalLayout_5.addWidget(self.RGBD)
		self.label_6 = QtGui.QLabel(self.frame_2)
		self.label_6.setObjectName("label_6")
		self.verticalLayout_5.addWidget(self.label_6)
		self.PO = QtGui.QSpinBox(self.frame_2)
		self.PO.setMaximum(512)
		self.PO.setObjectName("PO")
		self.verticalLayout_5.addWidget(self.PO)
		self.label_7 = QtGui.QLabel(self.frame_2)
		self.label_7.setObjectName("label_7")
		self.verticalLayout_5.addWidget(self.label_7)
		self.RS = QtGui.QSpinBox(self.frame_2)
		self.RS.setMaximum(32)
		self.RS.setObjectName("RS")
		self.verticalLayout_5.addWidget(self.RS)
		self.label_8 = QtGui.QLabel(self.frame_2)
		self.label_8.setObjectName("label_8")
		self.verticalLayout_5.addWidget(self.label_8)
		self.ART = QtGui.QSpinBox(self.frame_2)
		self.ART.setMaximum(64)
		self.ART.setObjectName("ART")
		self.verticalLayout_5.addWidget(self.ART)
		self.label_9 = QtGui.QLabel(self.frame_2)
		self.label_9.setObjectName("label_9")
		self.verticalLayout_5.addWidget(self.label_9)
		self.NOISE = QtGui.QSpinBox(self.frame_2)
		self.NOISE.setMaximum(99999)
		self.NOISE.setSingleStep(1000)
		self.NOISE.setObjectName("NOISE")
		self.verticalLayout_5.addWidget(self.NOISE)
		self.GENBUTTON = QtGui.QPushButton(self.frame_2)
		self.GENBUTTON.setObjectName("GENBUTTON")
		self.verticalLayout_5.addWidget(self.GENBUTTON)
		self.verticalLayout_5.setStretch(0, 4)
		self.verticalLayout_5.setStretch(1, 1)
		self.verticalLayout_5.setStretch(2, 4)
		self.verticalLayout_5.setStretch(3, 4)
		self.verticalLayout_5.setStretch(4, 4)
		self.verticalLayout_5.setStretch(5, 4)
		self.verticalLayout_5.setStretch(6, 4)
		self.verticalLayout_5.setStretch(7, 4)
		self.verticalLayout_5.setStretch(8, 4)
		self.verticalLayout_5.setStretch(9, 4)
		self.verticalLayout_5.setStretch(10, 4)
		self.verticalLayout_5.setStretch(11, 4)
		self.verticalLayout_5.setStretch(12, 4)
		self.verticalLayout_5.setStretch(13, 4)
		self.verticalLayout_5.setStretch(14, 4)
		self.horizontalLayout.addWidget(self.frame_2)
		spacerItem2 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
		self.horizontalLayout.addItem(spacerItem2)
		self.frame_3 = QtGui.QFrame(self.centralwidget)
		self.frame_3.setFrameShape(QtGui.QFrame.Box)
		self.frame_3.setFrameShadow(QtGui.QFrame.Sunken)
		self.frame_3.setObjectName("frame_3")
		self.verticalLayout_6 = QtGui.QVBoxLayout(self.frame_3)
		self.verticalLayout_6.setSpacing(18)
		self.verticalLayout_6.setObjectName("verticalLayout_6")
		self.label_10 = QtGui.QLabel(self.frame_3)
		sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
		sizePolicy.setHorizontalStretch(0)
		sizePolicy.setVerticalStretch(0)
		sizePolicy.setHeightForWidth(self.label_10.sizePolicy().hasHeightForWidth())
		self.label_10.setSizePolicy(sizePolicy)
		self.label_10.setAlignment(QtCore.Qt.AlignCenter)
		self.label_10.setObjectName("label_10")
		self.verticalLayout_6.addWidget(self.label_10)
		self.ADDBUTTON = QtGui.QPushButton(self.frame_3)
		self.ADDBUTTON.setObjectName("ADDBUTTON")
		self.verticalLayout_6.addWidget(self.ADDBUTTON)
		self.SCREENBUTTON = QtGui.QPushButton(self.frame_3)
		self.SCREENBUTTON.setObjectName("SCREENBUTTON")
		self.verticalLayout_6.addWidget(self.SCREENBUTTON)
		self.MULTIPLYBUTTON = QtGui.QPushButton(self.frame_3)
		self.MULTIPLYBUTTON.setObjectName("MULTIPLYBUTTON")
		self.verticalLayout_6.addWidget(self.MULTIPLYBUTTON)
		self.SUBTRACTBUTTON = QtGui.QPushButton(self.frame_3)
		self.SUBTRACTBUTTON.setObjectName("SUBTRACTBUTTON")
		self.verticalLayout_6.addWidget(self.SUBTRACTBUTTON)
		self.GRAINBUTTON = QtGui.QPushButton(self.frame_3)
		self.GRAINBUTTON.setObjectName("GRAINBUTTON")
		self.verticalLayout_6.addWidget(self.GRAINBUTTON)
		self.COLOR32BUTTON = QtGui.QPushButton(self.frame_3)
		self.COLOR32BUTTON.setObjectName("COLOR32BUTTON")
		self.verticalLayout_6.addWidget(self.COLOR32BUTTON)
		self.COLOR16BUTTON = QtGui.QPushButton(self.frame_3)
		self.COLOR16BUTTON.setObjectName("COLOR16BUTTON")
		self.verticalLayout_6.addWidget(self.COLOR16BUTTON)
		self.COLOR8BUTTON = QtGui.QPushButton(self.frame_3)
		self.COLOR8BUTTON.setObjectName("COLOR8BUTTON")
		self.verticalLayout_6.addWidget(self.COLOR8BUTTON)
		self.DIFFBUTTON = QtGui.QPushButton(self.frame_3)
		self.DIFFBUTTON.setObjectName("DIFFBUTTON")
		self.verticalLayout_6.addWidget(self.DIFFBUTTON)
		self.INVERTBUTTON = QtGui.QPushButton(self.frame_3)
		self.INVERTBUTTON.setObjectName("INVERTBUTTON")
		self.verticalLayout_6.addWidget(self.INVERTBUTTON)
		self.horizontalLayout.addWidget(self.frame_3)
		self.horizontalLayout.setStretch(0, 15)
		self.horizontalLayout.setStretch(1, 1)
		self.horizontalLayout.setStretch(2, 15)
		self.verticalLayout_3.addLayout(self.horizontalLayout)
		self.verticalLayout_3.setStretch(0, 2)
		self.verticalLayout_3.setStretch(1, 1)
		self.verticalLayout_3.setStretch(2, 15)
		self.horizontalLayout_2.addLayout(self.verticalLayout_3)
		self.IMAGESCENE = QtGui.QGraphicsScene()
		self.IMAGEVIEW = QtGui.QGraphicsView(self.IMAGESCENE)
		self.IMAGEVIEW.setObjectName("IMAGEVIEW")
		self.horizontalLayout_2.addWidget(self.IMAGEVIEW)
		MainWindow.setCentralWidget(self.centralwidget)
		self.statusbar = QtGui.QStatusBar(MainWindow)
		self.statusbar.setObjectName("statusbar")
		MainWindow.setStatusBar(self.statusbar)
		self.menuBar = QtGui.QMenuBar(MainWindow)
		self.menuBar.setGeometry(QtCore.QRect(0, 0, 1000, 21))
		self.menuBar.setObjectName("menuBar")
		self.menuFile = QtGui.QMenu(self.menuBar)
		self.menuFile.setObjectName("menuFile")
		MainWindow.setMenuBar(self.menuBar)
		self.actionLoad_Image = QtGui.QAction(MainWindow)
		self.actionLoad_Image.setObjectName("actionLoad_Image")
		self.actionSave = QtGui.QAction(MainWindow)
		self.actionSave.setObjectName("actionSave")
		self.menuFile.addAction(self.actionLoad_Image)
		self.menuFile.addAction(self.actionSave)
		self.menuBar.addAction(self.menuFile.menuAction())
		self.actionLoad_Image.triggered.connect(lambda: func_fastglitch.load_image(self.IMAGESCENE)) 
		self.actionSave.triggered.connect(lambda: func_fastglitch.save_image())
		self.GENBUTTON.clicked.connect(lambda: func_fastglitch.genImg(self.IMAGESCENE, self.RBA.value(), self.RGBD.value(),
			self.PO.value(), self.RS.value(), self.ART.value(), self.NOISE.value()))
		self.SCREENBUTTON.clicked.connect(lambda: func_fastglitch.screen(self.IMAGESCENE))
		self.MULTIPLYBUTTON.clicked.connect(lambda: func_fastglitch.logMult(self.IMAGESCENE))
		self.SUBTRACTBUTTON.clicked.connect(lambda: func_fastglitch.logSub(self.IMAGESCENE))
		self.ADDBUTTON.clicked.connect(lambda: func_fastglitch.add(self.IMAGESCENE))
		self.GRAINBUTTON.clicked.connect(lambda: func_fastglitch.Grain(self.IMAGESCENE))
		self.COLOR32BUTTON.clicked.connect(lambda: func_fastglitch.Quantize(self.IMAGESCENE, 32))
		self.COLOR16BUTTON.clicked.connect(lambda: func_fastglitch.Quantize(self.IMAGESCENE, 16))
		self.COLOR8BUTTON.clicked.connect(lambda: func_fastglitch.Quantize(self.IMAGESCENE, 8))
		self.COLOR32BUTTON.clicked.connect(lambda: func_fastglitch.Quantize(self.IMAGESCENE, 32))
		self.DIFFBUTTON.clicked.connect(lambda: func_fastglitch.differ(self.IMAGESCENE))
		self.INVERTBUTTON.clicked.connect(lambda: func_fastglitch.colorInvert(self.IMAGESCENE))

		self.retranslateUi(MainWindow)
		QtCore.QMetaObject.connectSlotsByName(MainWindow)


	def retranslateUi(self, MainWindow):
		MainWindow.setWindowTitle(QtGui.QApplication.translate("MainWindow", "FastGlitch", None, QtGui.QApplication.UnicodeUTF8))
		self.label.setText(QtGui.QApplication.translate("MainWindow", "FastGlitch 2.0 - Created by Lorelei Rosenkreuz!", None, QtGui.QApplication.UnicodeUTF8))
		self.label_2.setText(QtGui.QApplication.translate("MainWindow", "http://ranyakumo.xyz", None, QtGui.QApplication.UnicodeUTF8))
		self.label_3.setText(QtGui.QApplication.translate("MainWindow", "Generative Effects", None, QtGui.QApplication.UnicodeUTF8))
		self.label_4.setText(QtGui.QApplication.translate("MainWindow", "Random Byte Addition (0-16)", None, QtGui.QApplication.UnicodeUTF8))
		self.label_5.setText(QtGui.QApplication.translate("MainWindow", "RGB Displace (0-64)", None, QtGui.QApplication.UnicodeUTF8))
		self.label_6.setText(QtGui.QApplication.translate("MainWindow", "Pixel Offset (0-512)", None, QtGui.QApplication.UnicodeUTF8))
		self.label_7.setText(QtGui.QApplication.translate("MainWindow", "Row Slice (0-32)", None, QtGui.QApplication.UnicodeUTF8))
		self.label_8.setText(QtGui.QApplication.translate("MainWindow", "Artifact (0-64)", None, QtGui.QApplication.UnicodeUTF8))
		self.label_9.setText(QtGui.QApplication.translate("MainWindow", "Noise (0-99999)", None, QtGui.QApplication.UnicodeUTF8))
		self.GENBUTTON.setText(QtGui.QApplication.translate("MainWindow", "Generate", None, QtGui.QApplication.UnicodeUTF8))
		self.label_10.setText(QtGui.QApplication.translate("MainWindow", "Quick Effects", None, QtGui.QApplication.UnicodeUTF8))
		self.ADDBUTTON.setText(QtGui.QApplication.translate("MainWindow", "Add", None, QtGui.QApplication.UnicodeUTF8))
		self.SCREENBUTTON.setText(QtGui.QApplication.translate("MainWindow", "Screen", None, QtGui.QApplication.UnicodeUTF8))
		self.MULTIPLYBUTTON.setText(QtGui.QApplication.translate("MainWindow", "Multiply", None, QtGui.QApplication.UnicodeUTF8))
		self.SUBTRACTBUTTON.setText(QtGui.QApplication.translate("MainWindow", "Subtract", None, QtGui.QApplication.UnicodeUTF8))
		self.GRAINBUTTON.setText(QtGui.QApplication.translate("MainWindow", "Grain (very slow!)", None, QtGui.QApplication.UnicodeUTF8))
		self.COLOR32BUTTON.setText(QtGui.QApplication.translate("MainWindow", "32 Colors", None, QtGui.QApplication.UnicodeUTF8))
		self.COLOR16BUTTON.setText(QtGui.QApplication.translate("MainWindow", "16 Colors", None, QtGui.QApplication.UnicodeUTF8))
		self.COLOR8BUTTON.setText(QtGui.QApplication.translate("MainWindow", "8 Colors", None, QtGui.QApplication.UnicodeUTF8))
		self.DIFFBUTTON.setText(QtGui.QApplication.translate("MainWindow", "Differential", None, QtGui.QApplication.UnicodeUTF8))
		self.INVERTBUTTON.setText(QtGui.QApplication.translate("MainWindow", "Invert", None, QtGui.QApplication.UnicodeUTF8))
		self.menuFile.setTitle(QtGui.QApplication.translate("MainWindow", "File", None, QtGui.QApplication.UnicodeUTF8))
		self.actionLoad_Image.setText(QtGui.QApplication.translate("MainWindow", "Load Image", None, QtGui.QApplication.UnicodeUTF8))
		self.actionSave.setText(QtGui.QApplication.translate("MainWindow", "Save", None, QtGui.QApplication.UnicodeUTF8))



if __name__ == "__main__":
	import sys
	app = QtGui.QApplication(sys.argv)
	MainWindow = QtGui.QMainWindow()
	ui = Ui_MainWindow()
	ui.setupUi(MainWindow)
	MainWindow.show()
	sys.exit(app.exec_())

